// This file was automatically generated by snai.pe/go-varlink/codegen
// DO NOT EDIT

// The Varlink Service Interface is provided by every varlink service. It
// describes the service and the interfaces it implements.
package service

import (
	"context"
	"encoding/json"
	"fmt"
)

var _ = fmt.Errorf
var _ = json.RawMessage(nil)
var _ = context.Background

// InterfaceName is the fully-qualified name of this varlink interface.
const InterfaceName = `org.varlink.service`

// The requested interface was not found.
type InterfaceNotFoundError struct {
	Interface string `json:"interface"`
}

func (InterfaceNotFoundError) ErrorCode() string {
	return `org.varlink.service.InterfaceNotFound`
}

func (InterfaceNotFoundError) Error() string {
	return `The requested interface was not found.`
}

func InterfaceNotFound(interface_ string) InterfaceNotFoundError {
	var err_ InterfaceNotFoundError
	err_.Interface = interface_
	return err_
}

// The requested method was not found
type MethodNotFoundError struct {
	Method string `json:"method"`
}

func (MethodNotFoundError) ErrorCode() string {
	return `org.varlink.service.MethodNotFound`
}

func (MethodNotFoundError) Error() string {
	return `The requested method was not found`
}

func MethodNotFound(method string) MethodNotFoundError {
	var err_ MethodNotFoundError
	err_.Method = method
	return err_
}

// The interface defines the requested method, but the service does not
// implement it.
type MethodNotImplementedError struct {
	Method string `json:"method"`
}

func (MethodNotImplementedError) ErrorCode() string {
	return `org.varlink.service.MethodNotImplemented`
}

func (MethodNotImplementedError) Error() string {
	return `The interface defines the requested method, but the service does not implement it.`
}

func MethodNotImplemented(method string) MethodNotImplementedError {
	var err_ MethodNotImplementedError
	err_.Method = method
	return err_
}

// One of the passed parameters is invalid.
type InvalidParameterError struct {
	Parameter string `json:"parameter"`
}

func (InvalidParameterError) ErrorCode() string {
	return `org.varlink.service.InvalidParameter`
}

func (InvalidParameterError) Error() string {
	return `One of the passed parameters is invalid.`
}

func InvalidParameter(parameter string) InvalidParameterError {
	var err_ InvalidParameterError
	err_.Parameter = parameter
	return err_
}

// Client is denied access
type PermissionDeniedError struct{}

func (PermissionDeniedError) ErrorCode() string {
	return `org.varlink.service.PermissionDenied`
}

func (PermissionDeniedError) Error() string {
	return `Client is denied access`
}

func PermissionDenied() PermissionDeniedError {
	var err_ PermissionDeniedError
	return err_
}

// Method is expected to be called with 'more' set to true, but wasn't
type ExpectedMoreError struct{}

func (ExpectedMoreError) ErrorCode() string {
	return `org.varlink.service.ExpectedMore`
}

func (ExpectedMoreError) Error() string {
	return `Method is expected to be called with 'more' set to true, but wasn't`
}

func ExpectedMore() ExpectedMoreError {
	var err_ ExpectedMoreError
	return err_
}
